// Sales Representative HTTP surface.
import { Router } from 'express';
import { inTransaction, writeAuditAndOutbox } from '../../../infrastructure/database/transaction.js';
import { pool } from '../../../infrastructure/database/pool.js';
import { AppError, validate } from '../../../shared/http.js';
import { requireAuthentication, requireRole } from '../../../modules/identity/auth.middleware.js';
import { createQuoteSchema, idParams, revisionSchema } from './sales-rep.schemas.js';
import { createQuoteVersion, quoteNumber, routeApproval } from '../../../domains/sales-rep/quotation.service.js';

export const quoteRouter = Router();
quoteRouter.use(requireAuthentication);
const canAccess = (request, quote) => request.principal.roles.some((r)=>['admin','sales_manager','finance_operations'].includes(r)) || quote.owner_user_id === request.principal.id;
async function quoteForAccess(client, request, quoteId, lock=false) { const result=await client.query(`SELECT * FROM quotations WHERE id=$1${lock?' FOR UPDATE':''}`,[quoteId]); if(!result.rows[0])throw new AppError(404,'QUOTE_NOT_FOUND','Quotation was not found.'); if(!canAccess(request,result.rows[0]))throw new AppError(403,'FORBIDDEN','You cannot access this quotation.'); return result.rows[0]; }

quoteRouter.get('/', async(request,response,next)=>{try{const {rows}=await pool.query(`SELECT q.*,c.legal_name,qv.grand_total,ra.blended_risk_percent,ra.route FROM quotations q JOIN customers c ON c.id=q.customer_id LEFT JOIN quotation_versions qv ON qv.quotation_id=q.id AND qv.version_number=q.current_version_number LEFT JOIN risk_assessments ra ON ra.quotation_version_id=qv.id WHERE ($1::boolean OR q.owner_user_id=$2) ORDER BY q.updated_at DESC`,[request.principal.roles.some((r)=>['admin','sales_manager','finance_operations'].includes(r)),request.principal.id]);response.json({data:rows});}catch(error){next(error);}});
quoteRouter.post('/', requireRole('sales_rep','admin'), validate(createQuoteSchema), async(request,response,next)=>{try{const result=await inTransaction(async(client)=>{const input=request.validated.body;const customer=await client.query('SELECT * FROM customers WHERE id=$1',[input.customerId]);if(!customer.rows[0])throw new AppError(404,'CUSTOMER_NOT_FOUND','Customer was not found.');const {rows}=await client.query(`INSERT INTO quotations (quote_number,customer_id,owner_user_id,status,current_version_number) VALUES ($1,$2,$3,'draft',1) RETURNING *`,[quoteNumber(),input.customerId,request.principal.id]);const quote=rows[0];const fullCustomer=(await client.query(`SELECT c.*,ct.code AS tier_code,ct.entitlement_discount_percent,ct.policy_version AS tier_policy_version FROM customers c JOIN customer_tiers ct ON ct.id=c.tier_id WHERE c.id=$1`,[input.customerId])).rows[0];const {version,assessment}=await createQuoteVersion(client,{quotation:quote,customer:fullCustomer,input,actorUserId:request.principal.id,versionNumber:1});await writeAuditAndOutbox(client,{aggregateType:'quotation',aggregateId:quote.id,eventType:'quotation.created',actorUserId:request.principal.id,afterState:quote,metadata:{version:version.version_number,risk:assessment.blended_risk_percent}});return {quote,version,assessment};});response.status(201).json({data:result});}catch(error){next(error);}});
quoteRouter.get('/:quoteId', validate(idParams,'params'), async(request,response,next)=>{try{const quote=await quoteForAccess(pool,request,request.validated.params.quoteId);const version=(await pool.query('SELECT * FROM quotation_versions WHERE quotation_id=$1 AND version_number=$2',[quote.id,quote.current_version_number])).rows[0];const lines=(await pool.query('SELECT ql.*,p.sku,p.name,p.standard_cost FROM quotation_lines ql JOIN products p ON p.id=ql.product_id WHERE ql.quotation_version_id=$1 ORDER BY ql.line_number',[version.id])).rows;const risk=(await pool.query('SELECT * FROM risk_assessments WHERE quotation_version_id=$1',[version.id])).rows[0];const approvals=(await pool.query('SELECT * FROM approval_instances WHERE quotation_version_id=$1 ORDER BY sequence_number',[version.id])).rows;response.json({data:{quote,version,lines,risk,approvals}});}catch(error){next(error);}});
quoteRouter.post('/:quoteId/revisions', requireRole('sales_rep','admin'), validate(idParams,'params'), validate(revisionSchema), async(request,response,next)=>{try{const result=await inTransaction(async(client)=>{const quote=await quoteForAccess(client,request,request.validated.params.quoteId,true);const input=request.validated.body;if(quote.lock_version!==input.expectedLockVersion)throw new AppError(409,'QUOTE_VERSION_CONFLICT','Quotation was updated by another user.',{currentLockVersion:quote.lock_version});if(['paid','cancelled','expired','superseded'].includes(quote.status))throw new AppError(409,'QUOTE_NOT_EDITABLE','This quotation cannot be revised.');const customer=(await client.query(`SELECT c.*,ct.code AS tier_code,ct.entitlement_discount_percent,ct.policy_version AS tier_policy_version FROM customers c JOIN customer_tiers ct ON ct.id=c.tier_id WHERE c.id=$1`,[quote.customer_id])).rows[0];const nextVersion=quote.current_version_number+1;const {version,assessment}=await createQuoteVersion(client,{quotation:quote,customer,input,actorUserId:request.principal.id,versionNumber:nextVersion});await client.query(`UPDATE quotations SET current_version_number=$1,lock_version=lock_version+1,status='draft',last_activity_at=now(),updated_at=now() WHERE id=$2`,[nextVersion,quote.id]);await client.query(`UPDATE approval_instances SET status='superseded' WHERE quotation_id=$1 AND quotation_version_id<>$2 AND status='pending'`,[quote.id,version.id]);await writeAuditAndOutbox(client,{aggregateType:'quotation',aggregateId:quote.id,eventType:'quotation.revised',actorUserId:request.principal.id,metadata:{version:nextVersion,risk:assessment.blended_risk_percent}});return {version,assessment,lockVersion:quote.lock_version+1};});response.status(201).json({data:result});}catch(error){next(error);}});
quoteRouter.post('/:quoteId/submit', requireRole('sales_rep','admin'), validate(idParams,'params'), async(request,response,next)=>{try{const result=await inTransaction(async(client)=>{const quote=await quoteForAccess(client,request,request.validated.params.quoteId,true);const version=(await client.query('SELECT * FROM quotation_versions WHERE quotation_id=$1 AND version_number=$2',[quote.id,quote.current_version_number])).rows[0];const assessment=(await client.query('SELECT * FROM risk_assessments WHERE quotation_version_id=$1',[version.id])).rows[0];if(!version||!assessment)throw new AppError(409,'QUOTE_NOT_READY','Quotation needs a current version and risk assessment.');const status=await routeApproval(client,{quotation:quote,version,assessment,actorUserId:request.principal.id});return {quoteId:quote.id,versionNumber:version.version_number,status,assessment};});response.json({data:result});}catch(error){next(error);}});
quoteRouter.get('/:quoteId/timeline',validate(idParams,'params'),async(request,response,next)=>{try{const quote=await quoteForAccess(pool,request,request.validated.params.quoteId);const {rows}=await pool.query('SELECT * FROM audit_events WHERE quotation_id=$1 ORDER BY occurred_at DESC',[quote.id]);response.json({data:rows});}catch(error){next(error);}});
quoteRouter.get('/:quoteId/health',validate(idParams,'params'),async(request,response,next)=>{try{const quote=await quoteForAccess(pool,request,request.validated.params.quoteId);const {rows}=await pool.query('SELECT * FROM deal_health_assessments WHERE quotation_id=$1 ORDER BY assessed_at DESC LIMIT 1',[quote.id]);response.json({data:rows[0]??null});}catch(error){next(error);}});
