'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api, clearToken, getUser } from '@/lib/api';
import { Badge, Button, Card } from '@/components/ui';

type Quote = { id: string; quote_number: string; status: string; grand_total: string; currency_code: string; last_activity_at: string; lock_version?: number };
type Detail = Quote & { customer_name: string; lock_version: number; version?: { lines: Array<{ id: string; product_name: string; quantity: string; net_line_value: string }>; grand_total: string; currency_code: string } };
type Message = { id: string; origin: 'internal' | 'customer'; message_text: string; created_at: string; requested_discount_percent?: string };
type TierProgress = { tier_code?: string; tier_name?: string; entitlement_discount_percent: string; net_spend: string; completed_orders: number; tiers: Array<{code:string;display_name:string;qualification_spend:string;qualification_order_count:number}> };
const complete = new Set(['fulfilled', 'invoiced', 'partially_paid', 'paid']);

export default function CustomerPortalHome() {
  const router = useRouter(); const [quotes, setQuotes] = useState<Quote[]>([]); const [selected, setSelected] = useState<Detail | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [tier, setTier] = useState<TierProgress | null>(null); const [tab, setTab] = useState<'outstanding' | 'negotiations' | 'completed'>('outstanding'); const [message, setMessage] = useState(''); const [discount, setDiscount] = useState(''); const [error, setError] = useState('');
  const load = () => api.get<{ quotes: Quote[] }>('/portal/quotes').then((r) => setQuotes(r.quotes)).catch((e) => setError(e.message));
  useEffect(() => { const user = getUser(); if (!user?.roles.includes('customer_portal')) { router.replace('/'); return; } load(); api.get<{tier:TierProgress}>('/portal/tier').then(r=>setTier(r.tier)).catch(e=>setError(e.message)); }, [router]);
  const visible = useMemo(() => quotes.filter((q) => tab === 'completed' ? complete.has(q.status) : tab === 'negotiations' ? q.status === 'under_negotiation' : !complete.has(q.status)), [quotes, tab]);
  async function select(q: Quote) { try { const [detail, thread] = await Promise.all([api.get<{ quote: Detail }>(`/portal/quotes/${q.id}`), api.get<{ messages: Message[] }>(`/portal/quotes/${q.id}/messages`)]); setSelected(detail.quote); setMessages(thread.messages); setMessage(''); setDiscount(''); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'Could not open order.'); } }
  async function negotiate() { if (!selected || !message.trim()) return; try { await api.post(`/portal/quotes/${selected.id}/counter`, { lock_version: selected.lock_version, message_text: message, requested_discount_percent: discount ? Number(discount) : undefined }); await select(selected); load(); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'Could not send message.'); } }
  async function accept() { if (!selected) return; try { await api.post(`/portal/quotes/${selected.id}/accept`, { lock_version: selected.lock_version }); await select(selected); load(); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'Could not confirm order.'); } }
  return <main className="min-h-screen bg-gray-50"><header className="bg-white border-b"><div className="max-w-6xl mx-auto h-14 px-4 flex items-center"><span className="font-semibold text-gray-900">DealFlow<span className="text-brand">360</span></span><span className="ml-3 text-sm text-gray-500">Customer portal</span><button onClick={() => { clearToken(); router.replace('/'); }} className="ml-auto text-sm text-gray-500">Sign out</button></div></header><div className="max-w-6xl mx-auto p-4 md:p-8"><h1 className="text-2xl font-semibold text-gray-900">Your orders</h1><p className="mt-1 text-sm text-gray-500">Review current proposals, negotiate terms, and follow completed orders.</p>{error && <p className="mt-4 p-3 bg-red-50 rounded-lg text-sm text-red-700">{error}</p>}
    {tier && <Card className="mt-6 p-5 border-brand-100"><div className="flex justify-between gap-4"><div><p className="text-xs uppercase tracking-wide text-gray-500">Your customer tier</p><h2 className="mt-1 text-xl font-semibold capitalize text-gray-900">{tier.tier_name ?? 'No tier'}</h2><p className="text-sm text-gray-500">Discount entitlement: {Number(tier.entitlement_discount_percent).toFixed(0)}% (category limits may be lower)</p></div><div className="text-right text-sm text-gray-600"><p>{Number(tier.net_spend).toLocaleString()} completed spend</p><p>{tier.completed_orders} completed orders</p></div></div><div className="mt-4 grid md:grid-cols-3 gap-3">{tier.tiers.map(t=><div key={t.code} className="rounded-lg bg-gray-50 p-3 text-sm"><p className="font-medium capitalize">{t.display_name}</p><p className="text-xs text-gray-500 mt-1">Reach {Number(t.qualification_spend).toLocaleString()} spend or {t.qualification_order_count} orders</p></div>)}</div></Card>}
    <div className="mt-6 flex gap-2 border-b">{([['outstanding','Outstanding'],['negotiations','Negotiations'],['completed','Completed']] as const).map(([key,label]) => <button key={key} onClick={() => setTab(key)} className={`px-4 py-2 text-sm ${tab === key ? 'border-b-2 border-brand text-brand font-medium' : 'text-gray-500'}`}>{label}</button>)}</div>
    <div className="mt-5 grid lg:grid-cols-2 gap-5"><section className="space-y-3">{visible.length === 0 ? <Card className="p-5 text-sm text-gray-500">No {tab} orders.</Card> : visible.map((q) => <button key={q.id} onClick={() => select(q)} className="block text-left w-full"><Card className={`p-4 hover:border-brand ${selected?.id === q.id ? 'border-brand' : ''}`}><div className="flex justify-between gap-3"><div><p className="font-medium text-gray-900">{q.quote_number}</p><p className="text-sm text-gray-500 mt-1">Last updated {new Date(q.last_activity_at).toLocaleDateString()}</p></div><div className="text-right"><Badge variant={q.status === 'under_negotiation' ? 'yellow' : complete.has(q.status) ? 'green' : 'blue'}>{q.status.replaceAll('_', ' ')}</Badge><p className="mt-2 text-sm font-medium">{q.currency_code} {Number(q.grand_total).toFixed(2)}</p></div></div></Card></button>)}</section>
      <section>{selected ? <Card className="p-5"><div className="flex justify-between"><div><h2 className="font-semibold text-gray-900">{selected.quote_number}</h2><p className="text-sm text-gray-500">{selected.customer_name}</p></div><Badge variant="blue">{selected.status.replaceAll('_', ' ')}</Badge></div><div className="mt-5 space-y-2">{selected.version?.lines.map((line) => <div key={line.id} className="flex justify-between text-sm"><span>{line.product_name} × {line.quantity}</span><span>{selected.version?.currency_code} {Number(line.net_line_value).toFixed(2)}</span></div>)}</div><div className="mt-5 border-t pt-4"><h3 className="font-medium text-gray-800">Negotiation</h3><div className="mt-3 max-h-44 overflow-y-auto space-y-2">{messages.map((m) => <div key={m.id} className={`p-2 rounded text-sm ${m.origin === 'customer' ? 'bg-brand-50 ml-6' : 'bg-gray-100 mr-6'}`}><p>{m.message_text}</p>{m.requested_discount_percent && <p className="text-xs mt-1 text-gray-500">Requested discount: {m.requested_discount_percent}%</p>}</div>)}</div>{!complete.has(selected.status) && <div className="mt-4 space-y-2"><textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Ask a question or propose a change…" className="w-full border rounded-lg p-2 text-sm" rows={3} /><input value={discount} onChange={(e) => setDiscount(e.target.value)} type="number" min="0" max="100" placeholder="Optional requested discount %" className="w-full border rounded-lg p-2 text-sm" /><div className="flex gap-2"><Button variant="secondary" onClick={negotiate}>Send negotiation</Button>{['sent_to_customer','approved'].includes(selected.status) && <Button variant="primary" onClick={accept}>Confirm order</Button>}</div></div>}</div></Card> : <Card className="p-5 text-sm text-gray-500">Select an order to view its details or negotiate.</Card>}</section></div></div></main>;
}
