'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Button, Card, PageHeader } from '@/components/ui';
type Tier={id:string;code:string;display_name:string;entitlement_discount_percent:string;qualification_spend:string;qualification_order_count:number};
type Customer={id:string;legal_name:string;tier_code?:string;tier_id?:string};

export default function TierProgramPage(){
 const [tiers,setTiers]=useState<Tier[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [selected,setSelected]=useState('');const [tierId,setTierId]=useState('');const [reason,setReason]=useState('');const [error,setError]=useState('');
 const load=()=>Promise.all([api.get<{data:Tier[]}>('/admin/customer-tiers'),api.get<{data:Customer[]}>('/admin/customers')]).then(([t,c])=>{setTiers(t.data);setCustomers(c.data)}).catch(e=>setError(e.message));
 useEffect(()=>{load()},[]);
 async function saveTier(t:Tier){try{await api.put(`/admin/customer-tiers/${t.id}`,{displayName:t.display_name,entitlementDiscountPercent:Number(t.entitlement_discount_percent),qualificationSpend:Number(t.qualification_spend),qualificationOrderCount:Number(t.qualification_order_count)});load()}catch(e:unknown){setError(e instanceof Error?e.message:'Could not save tier');}}
 async function override(){if(!selected||reason.trim().length<3)return setError('Choose a customer and give a reason.');try{await api.put(`/admin/customers/${selected}/tier`,{tierId:tierId||null,reason});setReason('');load()}catch(e:unknown){setError(e instanceof Error?e.message:'Could not update customer tier');}}
 return <div className="max-w-5xl"><PageHeader title="Customer tier program" subtitle="Customers begin with no tier. Paid-order milestones can earn Bronze, Silver, and Gold; an admin can override any assignment."/>{error&&<p className="mb-4 p-3 text-sm bg-red-50 text-red-700 rounded">{error}</p>}
 <Card className="p-5 mb-6"><h2 className="font-semibold text-gray-900">Milestones and discount entitlement</h2><p className="text-sm text-gray-500 mt-1">A customer earns the highest tier where either completed spend or completed-order milestone is met. Category ceilings still cap the actual allowed line discount.</p><div className="mt-4 space-y-3">{tiers.map((tier,i)=><div key={tier.id} className="grid grid-cols-1 md:grid-cols-5 gap-3 items-end border-t pt-3"><p className="font-medium capitalize">{tier.code}</p><label className="text-xs">Tier discount %<input type="number" value={tier.entitlement_discount_percent} onChange={e=>setTiers(x=>x.map((v,n)=>n===i?{...v,entitlement_discount_percent:e.target.value}:v))} className="mt-1 w-full border rounded p-2"/></label><label className="text-xs">Spend milestone<input type="number" value={tier.qualification_spend} onChange={e=>setTiers(x=>x.map((v,n)=>n===i?{...v,qualification_spend:e.target.value}:v))} className="mt-1 w-full border rounded p-2"/></label><label className="text-xs">Completed orders<input type="number" value={tier.qualification_order_count} onChange={e=>setTiers(x=>x.map((v,n)=>n===i?{...v,qualification_order_count:Number(e.target.value)}:v))} className="mt-1 w-full border rounded p-2"/></label><Button onClick={()=>saveTier(tier)}>Save {tier.code}</Button></div>)}</div></Card>
 <Card className="p-5"><h2 className="font-semibold text-gray-900">Manual tier override</h2><div className="mt-4 grid md:grid-cols-4 gap-3 items-end"><label className="text-xs">Customer<select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-1 w-full border rounded p-2"><option value="">Select…</option>{customers.map(c=><option key={c.id} value={c.id}>{c.legal_name} ({c.tier_code??'no tier'})</option>)}</select></label><label className="text-xs">Assign tier<select value={tierId} onChange={e=>setTierId(e.target.value)} className="mt-1 w-full border rounded p-2"><option value="">No tier</option>{tiers.map(t=><option key={t.id} value={t.id}>{t.display_name}</option>)}</select></label><label className="text-xs">Reason<input value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 w-full border rounded p-2"/></label><Button variant="primary" onClick={override}>Apply override</Button></div></Card></div>
}
