'use client';

import { FormEvent, useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Button, Card, PageHeader, Table, Td, Tr } from '@/components/ui';
type Customer={id:string;legal_name:string;currency_code:string;tier_code?:string;tier_assignment_source:string;contact_count:number};
type Contact={id:string;email:string;display_name:string};

export default function CustomersAdminPage(){
 const [customers,setCustomers]=useState<Customer[]>([]);const [selected,setSelected]=useState<Customer|null>(null);const [contacts,setContacts]=useState<Contact[]>([]);const [error,setError]=useState('');const [customer,setCustomer]=useState({legalName:'',currencyCode:'USD'});const [contact,setContact]=useState({displayName:'',email:''});
 const load=()=>api.get<{data:Customer[]}>('/admin/customers').then(r=>setCustomers(r.data)).catch(e=>setError(e.message)); useEffect(()=>{load()},[]);
 async function addCustomer(e:FormEvent){e.preventDefault();try{await api.post('/admin/customers',customer);setCustomer({legalName:'',currencyCode:'USD'});load()}catch(e:unknown){setError(e instanceof Error?e.message:'Could not create customer');}}
 async function choose(c:Customer){setSelected(c);try{const r=await api.get<{data:Contact[]}>(`/admin/customers/${c.id}/contacts`);setContacts(r.data)}catch(e:unknown){setError(e instanceof Error?e.message:'Could not load contacts');}}
 async function addContact(e:FormEvent){e.preventDefault();if(!selected)return;try{await api.post(`/admin/customers/${selected.id}/contacts`,contact);setContact({displayName:'',email:''});choose(selected);load()}catch(e:unknown){setError(e instanceof Error?e.message:'Could not add contact');}}
 return <div className="max-w-6xl"><PageHeader title="Customers and portal contacts" subtitle="Create customer companies with no tier by default, then add the contacts who may create customer portal accounts."/>{error&&<p className="mb-4 p-3 bg-red-50 text-red-700 text-sm rounded">{error}</p>}
 <Card className="p-5 mb-6"><form onSubmit={addCustomer} className="flex flex-wrap gap-3 items-end"><label className="text-xs">Company name<input required value={customer.legalName} onChange={e=>setCustomer({...customer,legalName:e.target.value})} className="mt-1 border rounded p-2"/></label><label className="text-xs">Currency<input required maxLength={3} value={customer.currencyCode} onChange={e=>setCustomer({...customer,currencyCode:e.target.value.toUpperCase()})} className="mt-1 w-20 border rounded p-2"/></label><Button type="submit" variant="primary">Add customer</Button></form></Card>
 <div className="grid lg:grid-cols-2 gap-5"><Card><Table headers={['Customer','Tier','Contacts']} >{customers.map(c=><Tr key={c.id} clickable onClick={()=>choose(c)}><Td className="font-medium">{c.legal_name}</Td><Td className="capitalize">{c.tier_code??'No tier'}</Td><Td>{c.contact_count}</Td></Tr>)}</Table></Card><Card className="p-5"><h2 className="font-semibold">{selected?`Portal contacts for ${selected.legal_name}`:'Select a customer'}</h2>{selected&&<><form onSubmit={addContact} className="mt-4 grid gap-3"><input required placeholder="Contact name" value={contact.displayName} onChange={e=>setContact({...contact,displayName:e.target.value})} className="border rounded p-2 text-sm"/><input required type="email" placeholder="Contact email" value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})} className="border rounded p-2 text-sm"/><Button type="submit">Add portal contact</Button></form><div className="mt-5 space-y-2">{contacts.map(c=><p key={c.id} className="text-sm"><span className="font-medium">{c.display_name}</span> <span className="text-gray-500">{c.email}</span></p>)}</div><p className="mt-5 text-xs text-gray-500">Contacts use Customer Sign Up on the login page to choose their own password.</p></>}</Card></div></div>
}
