'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { api } from '@/lib/api';
import { Badge, Button, Card, PageHeader } from '@/components/ui';

type Line={product_id:string;product_name:string;sku:string;quantity:string;unit_price:string;line_discount_percent:string;allowed_discount_percent:string};
type Detail={case:{owner_role:string;status:string;last_handoff_reason:string|null};quotation:{quote_number:string;customer_name:string;customer_tier:string|null;lock_version:number;version:{currency_code:string;grand_total:string;version_number:number;lines:Line[]}};requests:Array<{id:string;status:string;counter_discount_percent:string|null;requested_delivery_date:string|null;customer_name:string;line_requests:Array<{line_id:string;comment:string}>}>;events:Array<{id:string;event_type:string;actor_name:string;from_role:string|null;to_role:string|null;reason:string|null;created_at:string}>;can_edit:boolean};

export default function NegotiationDetailPage(){
 const {id}=useParams<{id:string}>();const router=useRouter();const [detail,setDetail]=useState<Detail|null>(null);const [lines,setLines]=useState<Line[]>([]);const [reason,setReason]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 const load=()=>api.get<Detail>(`/negotiations/${id}`).then(r=>{setDetail(r);setLines(r.quotation.version.lines)}).catch(e=>setError(e.message)); useEffect(()=>{load()},[id]);
 async function send(){if(!detail)return;setSaving(true);try{await api.post(`/negotiations/${id}/revisions`,{expectedLockVersion:detail.quotation.lock_version,currencyCode:detail.quotation.version.currency_code,discountMode:'line',reason:'Negotiation revision',lines:lines.map(l=>({productId:l.product_id,quantity:Number(l.quantity),lineDiscountPercent:Number(l.line_discount_percent)}))});await load()}catch(e:unknown){setError(e instanceof Error?e.message:'Could not send offer')}finally{setSaving(false)}}
 async function forward(){if(reason.trim().length<3)return setError('Give Finance a handoff reason.');setSaving(true);try{await api.post(`/negotiations/${id}/forward-to-finance`,{reason});router.push('/negotiations')}catch(e:unknown){setError(e instanceof Error?e.message:'Could not forward negotiation')}finally{setSaving(false)}}
 if(!detail)return <div className="p-8 text-sm text-gray-500">Loading negotiation…</div>; const manager=detail.case.owner_role==='sales_manager';
 return <div className="max-w-5xl"><button onClick={()=>router.back()} className="text-sm text-gray-500 mb-3">← Back</button><PageHeader title={`Negotiation · ${detail.quotation.customer_name}`} subtitle={`${detail.quotation.quote_number} · ${detail.quotation.customer_tier??'No tier'} tier`} />
 {error&&<p className="my-4 p-3 rounded bg-red-50 text-red-700 text-sm">{error}</p>}<Card className="p-4 mt-4"><div className="flex justify-between"><div><p className="text-xs uppercase text-gray-500">Current owner</p><p className="font-semibold capitalize">{detail.case.owner_role.replace('_',' ')}</p></div><Badge variant="yellow">{detail.case.status}</Badge></div>{detail.case.last_handoff_reason&&<p className="mt-3 text-sm text-gray-600">Latest handoff: {detail.case.last_handoff_reason}</p>}</Card>
 <div className="grid lg:grid-cols-3 gap-5 mt-5"><div className="lg:col-span-2"><Card className="p-5"><h2 className="font-semibold">Current offer · v{detail.quotation.version.version_number}</h2><p className="text-sm text-gray-500 mt-1">{detail.quotation.version.currency_code} {Number(detail.quotation.version.grand_total).toFixed(2)}</p><div className="mt-4 space-y-3">{lines.map((line,i)=><div key={line.product_id} className="grid grid-cols-[1fr_88px_88px] gap-2 items-center text-sm border-t pt-3"><div><p className="font-medium">{line.product_name}</p><p className="text-xs text-gray-500">Allowed: {Number(line.allowed_discount_percent).toFixed(1)}%</p></div><input disabled={!detail.can_edit} type="number" min="1" value={line.quantity} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,quantity:e.target.value}:x))} className="border rounded p-2"/><input disabled={!detail.can_edit} type="number" min="0" max="100" value={line.line_discount_percent} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,line_discount_percent:e.target.value}:x))} className="border rounded p-2"/></div>)}</div>{detail.can_edit&&<div className="mt-5 flex gap-2"><Button onClick={send} disabled={saving}>{saving?'Sending…':'Send revised offer'}</Button>{manager&&<><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason to involve Finance" className="border rounded px-3 text-sm flex-1"/><Button variant="secondary" onClick={forward} disabled={saving}>Forward to Finance</Button></>}</div>}</Card></div><div className="space-y-4"><Card className="p-4"><h2 className="text-sm font-semibold">Customer requests</h2>{detail.requests.map(r=><div key={r.id} className="mt-3 border-t pt-3 text-sm"><div className="flex justify-between"><span>{r.customer_name}</span><Badge variant="yellow">{r.status}</Badge></div><p className="text-xs mt-1">Discount: {r.counter_discount_percent??'—'}% · Delivery: {r.requested_delivery_date??'—'}</p>{r.line_requests.map((x,i)=><p key={i} className="mt-2 text-gray-600">{x.comment}</p>)}</div>)}</Card><Card className="p-4"><h2 className="text-sm font-semibold">Handoff history</h2>{detail.events.map(e=><p key={e.id} className="mt-2 text-xs text-gray-600">{new Date(e.created_at).toLocaleString()} · {e.event_type.replaceAll('_',' ')}{e.reason?`: ${e.reason}`:''}</p>)}</Card></div></div></div>
}
